- name: Import keygen tasks
  delegate_to: localhost
  run_once: true
  become: false
  vars:
    ca_key_name: "{{ ca_key_path | basename }}"
  ansible.builtin.import_tasks: keygen.yml
  tags:
    - ca_keygen


- name: Distribute CA public key to all servers
  ansible.builtin.copy:
    src: "./files/{{ ca_key_path | basename }}.pub"
    dest: "{{ ca_key_path }}.pub"
    owner: root
    group: root
    mode: '0644'
