- name: Generate Gateway CA key if not exists
  when: "'gateway' in group_names"
  run_once: true
  community.crypto.openssh_keypair:
    path: "{{ ca_key_path }}"
    type: rsa
    size: 4096
    state: present
    regenerate: never
- name: Fetch file from gateway
  when: "'gateway' in group_names"
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: ./files/
    flat: true
    mode: '0600'
  loop:
    - "{{ ca_key_path }}"
    - "{{ ca_key_path }}.pub"
- name: Distribute CA public key to all servers
  when: "'gateway' not in group_names"
  ansible.builtin.copy:
    src: "./files/{{ ca_key_path | basename }}.pub"
    dest: "{{ ca_key_path }}.pub"
    owner: root
    group: root
    mode: '0644'


- name: Create directories for users' ssh keys
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.file:
    path: "files/{{ item.username }}"
    state: directory
    mode: '0755'
  loop: "{{ ssh_users }}"
- name: Change ca keys permission
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.file:
    path: "files/{{ item }}"
    state: file
    mode: '0600'
  loop:
    - "{{ ca_key_path | basename }}"
    - "{{ ca_key_path | basename }}.pub"
- name: Generate user ssh key pairs
  delegate_to: localhost
  run_once: true
  become: false
  community.crypto.openssh_keypair:
    path: "files/{{ item.username }}/id_rsa"
    type: rsa
    size: 4096
    state: present
    regenerate: never
  loop: "{{ ssh_users }}"
- name: Sign user public keys with CA
  delegate_to: localhost
  run_once: true
  become: false
  community.crypto.openssh_cert:
    type: user
    path: "files/{{ item.username }}/id_rsa.cert"
    public_key: "files/{{ item.username }}/id_rsa.pub"
    signing_key: "files/{{ ca_key_path | basename }}"
    valid_from: always
    valid_to: "+{{ cert_validity_week }}w"
    principals: "{{ [item.username] + item.groups }}"
    identifier: "{{ item.username }}"
    state: present
  loop: "{{ ssh_users }}"
- name: Generate SSH config for users
  delegate_to: localhost
  run_once: true
  become: false
  ansible.builtin.template:
    src: ssh_config.j2
    dest: "files/{{ item.username }}/config"
    mode: '0644'
  loop: "{{ ssh_users }}"
