- name: Manage users on gateway
  ansible.builtin.import_tasks: user-manage.yml
  become: true
  tags:
    - user_manager

- name: Generate SSH CA key pair
  ansible.builtin.import_tasks: key-manage.yml
  become: true
  tags:
    - ca_keygen

- name: Configure SSH on gateway
  ansible.builtin.import_tasks: sshd-config.yml
  become: true
  tags:
    - config_sshd
  notify: Restart ssh
