- name: Manage users on gateway
  ansible.builtin.import_tasks: user-manage.yml
  become: true
  tags:
    - user_manager

- name: Generate SSH CA key pair
  ansible.builtin.import_tasks: key-manage.yml
  become: true
  tags:
    - ca_keygen

- name: Configure SSH on gateway
  ansible.builtin.import_tasks: sshd-gateway-config.yml
  become: true
  run_once: true
  tags:
    - config_gateway
  when: "'gateway' in group_names"
  notify: Restart ssh

- name: Configure SSH on servers
  ansible.builtin.import_tasks: sshd-servers-config.yml
  become: true
  run_once: true
  tags:
    - config_servers
  when: "'gateway' not in group_names"
  notify: Restart ssh
