---

- name: Config the Gateway ssh daemon
  ansible.builtin.template:
    src: gateway_sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: '0644'

- name: Ensure AuthorizedPrincipalsFile directory exists
  ansible.builtin.file:
    path: /etc/ssh/auth_principals
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set up auth_principals for each user
  ansible.builtin.copy:
    content: |
      {{ item.username }}
    dest: "/etc/ssh/auth_principals/{{ item.username }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ssh_users }}"

- name: Set up root auth_principals file for admins
  ansible.builtin.copy:
    content: |
      {% for item in ssh_users %}
      {% if 'admin' in item.groups %}
      {{ item.username }}
      {% endif %}
      {% endfor %}
    dest: "/etc/ssh/auth_principals/ubuntu"
    owner: root
    group: root
    mode: '0644'
