---

- name: Config the Gateway ssh daemon
  ansible.builtin.template:
    src: servers_sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: '0644'

- name: Ensure AuthorizedPrincipalsFile directory exists
  ansible.builtin.file:
    path: /etc/ssh/auth_principals
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set up auth_principals for each user
  ansible.builtin.copy:
    content: |
      {{ item.username }}
      {% for g in item.groups %}
      {{ g }}
      {% endfor %}
    dest: "/etc/ssh/auth_principals/{{ item.username }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ssh_users }}"

- name: Set up first login script
  ansible.builtin.copy:
    src: ssh-wrapper.sh
    dest: "/usr/local/bin/ssh_wrapper.sh"
    owner: root
    group: root
    mode: '0755'
