---
- name: Create directories and copy configs
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create storage directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/gateway/ssh"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/gateway/home"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/gateway/tmp"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/gateway/var/tmp"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/client/ssh"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/client/home"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/client/tmp"
        - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/client/var/tmp"

    - name: Copy sshd_config
      template:
        src: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/templates/sshd_config.j2"
        dest: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/default/.storage/{{item}}/ssh/sshd_config"
        mode: '0644'
      loop:
        - gateway
        - client