---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if SSH service is running
      service:
        name: ssh
        state: started
      register: ssh_service
      failed_when: not ssh_service.status.ActiveState == "active"

    - name: Verify SSH port is listening
      wait_for:
        port: 22
        state: started
        timeout: 10

    - name: Check SSH configuration files
      stat:
        path: "{{ item }}"
      loop:
        - /etc/ssh/sshd_config
        - /etc/ssh/trusted-user-ca-keys.pem
        - /etc/ssh/auth_principals
      register: ssh_files
      failed_when: not item.stat.exists