---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_remote_tmp: /tmp

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: ../../
