---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: gateway
    image: geerlingguy/docker-ubuntu2204-ansible
    privileged: true
    pre_build_image: true
    command: "/usr/sbin/init"
    capabilities:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    environment:
      TESTENV: molecule
      LC_ALL: C.UTF-8

  - name: client1
    image: geerlingguy/docker-ubuntu2204-ansible
    privileged: true
    pre_build_image: true
    command: "/usr/sbin/init"
    capabilities:
      - ALL
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    environment:
      TESTENV: molecule
      LC_ALL: C.UTF-8

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../"
    ANSIBLE_CONFIG: ${MOLECULE_SCENARIO_DIRECTORY}/ansible.cfg
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    host_vars:
      gateway:
        ansible_user: root
      client1:
        ansible_user: root
  playbooks:
    converge: converge.yml
    verify: verify.yml
    cleanup: cleanup.yml
verifier:
  name: ansible
