---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: gateway
    image: devdotnetorg/openssh-server:ubuntu
    pre_build_image: true
    privileged: true
    command: /usr/sbin/sshd -D
    published_ports:
      - "222:22"
    environment:
      USER_PASSWORD: "654321"
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/.storage/gateway/ssh:/etc/ssh
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/.storage/gateway/home:/home
    groups:
      - gateway      
  - name: client
    image: devdotnetorg/openssh-server:ubuntu
    pre_build_image: true
    privileged: true
    command: /usr/sbin/sshd -D
    environment:
      USER_PASSWORD: "654321"
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/.storage/client/ssh:/etc/ssh
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/.storage/client/home:/home
    groups:
      - client

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}
  inventory:
    group_vars:
      all:
        ansible_user: root

verifier:
  name: ansible

