---
- name: Verify
  hosts: all
  tasks:
    - name: Check SSH configuration
      command: sshd -T
      register: sshd_config
      changed_when: false

    - name: Verify SSH configuration is correct
      assert:
        that: 
          - "'trustedusercakeys /etc/ssh/trusted-user-ca-keys.pem' in sshd_config.stdout.lower()"
          - "'authorizedprincipalsfile /etc/ssh/auth_principals/%u' in sshd_config.stdout.lower()"